// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TimeSystem","status":true,"description":"Time system","parameters":{"debug":"false"}},
{"name":"FriendStateSystem","status":true,"description":"Friend State Controller","parameters":{"debug":"false"}},
{"name":"FarmingSystem","status":true,"description":"Farm System","parameters":{"debug":"false"}}
];
