// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"FarmingSystem","status":true,"description":"","parameters":{}},
{"name":"TimeSystem","status":true,"description":"Time system","parameters":{"debug":"false"}}
];
