// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TimeSystem","status":true,"description":"Time system","parameters":{"debug":"false"}},
{"name":"FarmingSystem","status":true,"description":"","parameters":{"成熟时间":"60"}}
];
